### ISSUE TITLE
ERROR: Failed to download Chromium r555668!

### ISSUE THREAD

**Issue by RicoLiu** [pod4g/hiper#10]
When i run `npm install hiper -g`, it has this error log:
```javascript
ERROR: Failed to download Chromium r555668! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:628:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```
How to  fix it

**Comment by bdoner** [comment]
This might give you a clue. Not sure if it's a solution.

https://github.com/GoogleChrome/puppeteer/issues/2173

**Comment by bsatria** [comment]
same issue here

Linux Mint 18.2
Node 10.0.0
Npm 6.0.1

**Comment by wanmaoor** [comment]
if you are in Linux, you can use this command like this: `sudo npm install hiper -g --save hiper --ignore-scripts`.it can skip download Chromium.because of the GFW...
