### ISSUE TITLE
Getting an issue when executing Hiper

### ISSUE THREAD

**Issue by asfo** [pod4g/hiper#24]
I recently installed Hiper and this issue is showing everytime I try to use it...

```
C:\Users\theas\AppData\Roaming\npm\node_modules\hiper\src\index.js:36
performance.run(opts).then(async statisticData => {
                           ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
```

**Comment by rinka0414** [comment]
same here, I'm using mac OS, and install hiper with npm

**Comment by pod4g** [comment]
The following environments are required：
```
node >= 8.0.0
npm >= 5.0.0
```
Please update the version.

**Comment by rinka0414** [comment]
:blush:thanks, I updated my node from v5 to v10, and hiper works fine now!

**Comment by asfo** [comment]
I support @rinka0414. The requirements should be at README :)

The update fixed my issue.

Thanks.
