### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by Nicksxs** [pod4g/hiper#7]
i try `hiper --help`
output:
```
/usr/local/lib/node_modules/hiper/src/index.js:24
performance.run(opts).then(async statisticData => {
                           ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

node version:
v6.11.2
npm version:
5.6.0
mac os 10.12.6

**Comment by pod4g** [comment]
Hi, please upgrade your Node.js version to `>=8.1.2`, your version too low and not support `async/await`.  thank you for use

**Comment by shadeofgod** [comment]
@pod4g 

it might be better if it can run the version check at first and output a readable warning for more friendly experience.

I can create a pull request for that, what do you think?

**Comment by pod4g** [comment]
@shadeofgod nice advise, thanks
